--these are the commands that hibernate executes
create table APP_PAGE (ID bigint not null, ACTION varchar, DESCRIPTION varchar, primary key (ID))
create table APP_PAGE_ROLES (PAGE_ID bigint not null, ROLE_ID bigint not null, primary key (PAGE_ID, ROLE_ID))
create table APP_ROLE (ID bigint not null, DESCRIPTION varchar, primary key (ID))
create table APP_SETTINGS (ID bigint not null, SETUP_DATE datetime, primary key (ID))
create table APP_USER_ROLES (USER_ID varchar not null, ROLE_ID bigint not null, primary key (USER_ID, ROLE_ID))
create table APP_USERS (USERNAME varchar not null, ACTIVE integer, BIRTHDATE date, EMAIL varchar, PASSWD varchar, NAME varchar, SURNAME varchar, primary key (USERNAME))
create table EXAMPLE_FOO (ID bigint not null, ADDRESS varchar, AGE double, BIRTHDAY date, HEIGHT integer, NAME varchar, primary key (ID))
create table EXAMPLE_FOO_EXAMPLE_FOO (Foo_ID bigint not null, foos_ID bigint not null)
create table hibernate_sequence (next_val bigint)
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
insert into hibernate_sequence values ( 1 )
--not supported by SQLite:
alter table APP_PAGE_ROLES add constraint UK_rqed5v0m5imuqqjc2prxoqey3 unique (ROLE_ID)
alter table APP_USER_ROLES add constraint UK_6e9ql67g9uttas0i3uwigpn4m unique (ROLE_ID)
alter table EXAMPLE_FOO_EXAMPLE_FOO add constraint UK_ffuqy3auq4ac1jey9csjxloft unique (foos_ID)
